version: '3.8'

services:
  discovery:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      
  forum:
    image: td6forum
    ports:
      - "8082:8080"
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery
  
  authentification:
    image: td6authentification
    ports:
      - "8081:8080"
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery

  gateway:
    image: td6gateway
    ports:
      - "8080:8080"
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery