version: '3.8'

services:
  discovery:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    networks:
      - my-network
    hostname: discovery
      
  forum:
    image: td6-forum
    restart: always
    environment:
      - CONSUL_HOST=discovery 
      - CONSUL_PORT=8500
    depends_on:
      - discovery
    networks:
      - my-network
    hostname: forum
  
  authentification:
    image: td6-authentification
    restart: always
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
    depends_on:
      - discovery
    networks:
      - my-network
    hostname: authentification

  gateway:
    image: td6-gateway
    ports:
      - "8080:8080"
    restart: always
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
    depends_on:
      - discovery
    networks:
      - my-network
    hostname: gateway

networks:
  my-network:
    driver: bridge
