spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: service-authentification
          uri: lb://service-authentification
          predicates:
            - Path=/service1/**
        - id: service-forum
          uri: lb://service-forum
          predicates:
            - Path=/service2/**
    consul:
      port: ${CONSUL_PORT:8500}
      host: ${CONSUL_HOST:localhost}
server:
  port: 8080


# spring.cloud.consul.port=${CONSUL_PORT:8500}
# spring.cloud.consul.host=${CONSUL_HOST:localhost}